#!/usr/bin/env python3
import argparse
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
DATA = ROOT / 'data'
OUT = ROOT / 'functions' / 'wl' / 'generated'


def load(name):
    return json.loads((DATA / name).read_text())


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--mode', default='tiny', choices=['tiny', 'prototype', 'dev', 'full'])
    args = parser.parse_args()

    messages = load('messages.json')
    arcs = load('arcs.json')
    OUT.mkdir(parents=True, exist_ok=True)

    cap = {'tiny': 20, 'prototype': 80, 'dev': 200, 'full': 500}.get(args.mode, 20)
    for m in messages[:cap]:
        channel = m['channel']
        p = OUT / f"message_{m['numeric_id']:04d}.mcfunction"
        payload = (
            "# AUTO-GENERATED by WorldLore Archive Generator\n"
            f"# source: {m['id']}\n"
            "# budget: max_commands=3 max_blocks=0 max_summons=0\n"
            "# DO NOT EDIT GENERATED FILE DIRECTLY\n"
            f"tellraw @a[r=32] {{\"rawtext\":[{{\"text\":\"[{channel}] {m['text']}\"}}]}}\n"
        )
        p.write_text(payload)

    idx = OUT / 'arc_index.mcfunction'
    lines = [
        '# AUTO-GENERATED by WorldLore Archive Generator',
        '# source: arcs.json',
        '# budget: max_commands=20 max_blocks=0 max_summons=0',
        '# DO NOT EDIT GENERATED FILE DIRECTLY',
    ]
    for a in arcs:
        lines.append(f"# {a['id']}")
    idx.write_text('\n'.join(lines) + '\n')

    print(f"generated_mode={args.mode} messages={min(cap, len(messages))} arcs={len(arcs)}")


if __name__ == '__main__':
    main()
